<?php require_once 'app/include/header.php'; 
include "app/controllers/buy-strategy.php";
session_start();
if (!isset($_SESSION['id'])) {
    header('Location: index.php');
    exit();
}
?>
<section class="lk-user-main">
  <div class="container">

    <div class="left-col">
      <?php require_once 'inc/lk/user-info.php'; ?>
      <?php require_once 'inc/lk/left-menu.php'; ?>
      <div class="calendar-wrapper">
        <button id="btnPrev" type="button"><img src="assets/img/calendar-left.svg" alt="prev"></button>
        <button id="btnNext" type="button"><img src="assets/img/calendar-right.svg" alt="next"></button>
        <div id="divCal"></div>
      </div>
    </div>

    <div class="right-col">
      <!-- <div class="widgets">
                    <span>место для виджетов</span>
                </div> -->
      <div class="security">
        <h1>Security</h1>
        <div class="two-factor-info">
          <h2>Тwo-factor authentication</h2>
          <p>
            Two-factor authentication is a security method that requires two different ways of confirming a user's
            identity
            before allowing access to a system. This may involve entering a password and sending a confirmation code to
            a
            pre-registered phone or email address.
          </p>
        </div>
        <div class="df">
          <div class="google-auth">
            <h2>Google authentication</h2>
            <p>
              Google authentication is a form of two-factor authentication provided by Google. It requires users to
              enter their
              password and a one-time code generated by an application on their smartphone. This method provides an
              extra layer
              of security to protect user accounts from unauthorized access.
            </p>
            <div class="switch-btn"></div>
          </div>
          <div class="sms-auth">
            <h2>SMS</h2>
            <p>
              Two-factor authentication via SMS is a security method that requires a user to enter a password and
              receive a one-time
              ode sent to a registered phone via SMS. This method provides an additional level of protection against
              unauthorized
              access to the user's account.
            </p>
            <div class="switch-btn"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<?php require_once 'app/include/footer.php'; ?>